server:
  port: 8080

spring:
  #关闭spring-session
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.203.238:3306/pay?userUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1qaz@WSX
  #redis 配置
  redis:
    host: 192.168.3.19
    #关闭spring-security
    timeout: 2000
#自定义登陆页面
wangmike:
  security:
    browser:
      loginType: JSON
    code:
      image:
        length: 6
        width: 100
        url: /user
#      loginPage: /demo-signIn.html
